### ISSUE TITLE
[BUG,严重]打包后notification不起作用

### ISSUE THREAD

**Issue by Luna-Grace** [DuckDuckStudio/Fufu_Tools#48]
使用到了notification的工具
- Tools\【实验性工具】\休息一下\休息一下.pyw
- Tools\连接检测\网络连接检测.py
- Tools\连接检测\GitHub连接检测.py

**Comment by WXZing** [comment]
报错信息：
```
Traceback (most recent call last):
  File "休息一下.pyw", line 14, in <module>
    notification.notify(
  File "plyer\facades\notification.py", line 84, in notify
  File "plyer\facades\notification.py", line 93, in _notify
NotImplementedError: No usable implementation found!
```

**Comment by DuckDuckStudio** [comment]
打包时请添加`--hidden-import plyer.platforms.win.notification`，这不是我的问题...

**Comment by DuckDuckStudio** [comment]
完整命令
```bash
pyinstaller --onefile --hidden-import plyer.platforms.win.notification --noconsole -i "ico.ico" --distpath=. xxx.pyw
pyinstaller --onefile --hidden-import plyer.platforms.win.notification -i "ico.ico" --distpath=. xxx.py
```

**Comment by DuckDuckStudio** [comment]
已在DEV-PACK中设置特别项
